// Generated by python/scripts/export_schemas.py.
// Do not edit by hand.

export type ExitRuleType = 'stop_loss_fixed' | 'take_profit_fixed' | 'trailing_stop_pct' | 'trailing_stop_atr' | 'time_stop';
export type ExitRuleScope = 'position';
export type ExitRuleAction = 'exit_full';
export type ExitRulePriceField = 'open' | 'high' | 'low' | 'close';
export type ExitRuleReference = 'entry_price' | 'highest_since_entry';
export type IntrabarConflictPolicy = 'stop_first' | 'take_profit_first' | 'priority_order';
export type RegimeCode = 'trending_bull' | 'trending_bear' | 'choppy_mean_reversion' | 'high_vol' | 'unclassified';
export type RegimeBlockedAction = 'skip_entries' | 'skip_rebalance';
export type UniverseSource = 'postgres_gold';
export type UniverseGroupOperator = 'and' | 'or';
export type UniverseConditionOperator = 'eq' | 'ne' | 'gt' | 'gte' | 'lt' | 'lte' | 'in' | 'not_in' | 'is_null' | 'is_not_null';
export type UniverseFieldId = 'market.close' | 'security.is_active' | 'security.sector' | 'security.delisted_at' | 'market.trade_date' | 'market.timestamp' | 'returns.return_20d' | 'returns.return_126d' | 'quality.piotroski_f_score' | 'earnings.surprise_pct';
export type UniverseValue = string | number | boolean;
export type UniverseValueKind = 'string' | 'number' | 'boolean' | 'date' | 'datetime';
export type RankingTransformType = 'percentile_rank' | 'zscore' | 'minmax' | 'clip' | 'winsorize' | 'coalesce' | 'log1p' | 'negate' | 'abs';
export type RankingDirection = 'asc' | 'desc';
export type RankingMissingValuePolicy = 'exclude' | 'zero';
export type RegimeStatus = 'confirmed' | 'transition' | 'unclassified';
export type TrendState = 'positive' | 'negative' | 'near_zero';
export type CurveState = 'contango' | 'flat' | 'inverted';
export type RunStatus = 'queued' | 'running' | 'completed' | 'failed';
export type BacktestLookupState = 'not_run' | 'queued' | 'running' | 'completed' | 'failed';
export type BacktestStreamEventType = 'accepted' | 'status' | 'heartbeat' | 'completed' | 'failed';
export type TradeRole = 'entry' | 'rebalance_increase' | 'rebalance_decrease' | 'exit';
export type UniverseNode = UniverseGroup | UniverseCondition;

export interface ExitRule {
  id: string;
  type: ExitRuleType;
  scope: ExitRuleScope;
  priceField?: ExitRulePriceField | null;
  value?: number | null;
  atrColumn?: string | null;
  priority?: number | null;
  action: ExitRuleAction;
  minHoldBars: number;
  reference?: ExitRuleReference | null;
}

export interface UniverseCondition {
  kind: 'condition';
  field: UniverseFieldId;
  operator: UniverseConditionOperator;
  value?: string | number | boolean | null;
  values?: UniverseValue[] | null;
}

export interface UniverseFieldDefinition {
  id: UniverseFieldId;
  label: string;
  valueKind: UniverseValueKind;
  operators: UniverseConditionOperator[];
}

export interface UniverseCatalogResponse {
  source: UniverseSource;
  fields: UniverseFieldDefinition[];
}

export interface UniversePreviewResponse {
  source: UniverseSource;
  symbolCount: number;
  sampleSymbols: string[];
  fieldsUsed: UniverseFieldId[];
  warnings: string[];
}

export interface UniverseGroup {
  kind: 'group';
  operator: UniverseGroupOperator;
  clauses: UniverseNode[];
}

export interface UniverseDefinition {
  source: UniverseSource;
  root: UniverseGroup;
}

export interface TargetGrossExposureByRegime {
  trending_bull: number;
  trending_bear: number;
  choppy_mean_reversion: number;
  high_vol: number;
  unclassified: number;
}

export interface RegimePolicy {
  modelName: string;
  targetGrossExposureByRegime: TargetGrossExposureByRegime;
  blockOnTransition: boolean;
  blockOnUnclassified: boolean;
  honorHaltFlag: boolean;
  onBlocked: RegimeBlockedAction;
}

export interface StrategyConfig {
  universeConfigName?: string | null;
  universe?: UniverseDefinition | null;
  rebalance: string;
  longOnly: boolean;
  topN: number;
  lookbackWindow: number;
  holdingPeriod: number;
  costModel: string;
  rankingSchemaName?: string | null;
  regimePolicy?: RegimePolicy | null;
  intrabarConflictPolicy: IntrabarConflictPolicy;
  exits: ExitRule[];
}

export interface RankingTransform {
  type: RankingTransformType;
  params: Record<string, string | number | boolean | null>;
}

export interface RankingFactor {
  name: string;
  table: string;
  column: string;
  weight: number;
  direction: RankingDirection;
  missingValuePolicy: RankingMissingValuePolicy;
  transforms: RankingTransform[];
}

export interface RankingGroup {
  name: string;
  weight: number;
  factors: RankingFactor[];
  transforms: RankingTransform[];
}

export interface RankingSchemaConfig {
  universeConfigName?: string | null;
  groups: RankingGroup[];
  overallTransforms: RankingTransform[];
}

export interface RankingPreviewRow {
  symbol: string;
  rank: number;
  score: number;
}

export interface RankingMaterializationSummary {
  runId: string;
  strategyName: string;
  rankingSchemaName: string;
  rankingSchemaVersion: number;
  outputTableName: string;
  startDate?: string | null;
  endDate?: string | null;
  rowCount: number;
  dateCount: number;
}

export interface RegimeModelConfig {
  trendPositiveThreshold: number;
  trendNegativeThreshold: number;
  curveContangoThreshold: number;
  curveInvertedThreshold: number;
  highVolEnterThreshold: number;
  highVolExitThreshold: number;
  bearVolMin: number;
  bearVolMaxExclusive: number;
  bullVolMaxExclusive: number;
  choppyVolMin: number;
  choppyVolMaxExclusive: number;
  haltVixThreshold: number;
  haltVixStreakDays: number;
  precedence: RegimeCode[];
}

export interface RegimeSnapshot {
  as_of_date: string;
  effective_from_date: string;
  model_name: string;
  model_version: number;
  regime_code: RegimeCode;
  regime_status: RegimeStatus;
  matched_rule_id?: string | null;
  halt_flag: boolean;
  halt_reason?: string | null;
  spy_return_20d?: number | null;
  rvol_10d_ann?: number | null;
  vix_spot_close?: number | null;
  vix3m_close?: number | null;
  vix_slope?: number | null;
  trend_state?: TrendState | null;
  curve_state?: CurveState | null;
  vix_gt_32_streak?: number | null;
  computed_at?: string | null;
}

export interface RegimeInputRow {
  as_of_date: string;
  spy_close?: number | null;
  return_1d?: number | null;
  return_20d?: number | null;
  rvol_10d_ann?: number | null;
  vix_spot_close?: number | null;
  vix3m_close?: number | null;
  vix_slope?: number | null;
  trend_state?: TrendState | null;
  curve_state?: CurveState | null;
  vix_gt_32_streak?: number | null;
  inputs_complete_flag: boolean;
  computed_at?: string | null;
}

export interface RegimeTransitionRow {
  model_name: string;
  model_version: number;
  effective_from_date: string;
  prior_regime_code?: RegimeCode | null;
  new_regime_code: RegimeCode;
  trigger_rule_id?: string | null;
  computed_at?: string | null;
}

export interface RegimeModelSummary {
  name: string;
  description?: string;
  version: number;
  updated_at?: string | null;
  active_version?: number | null;
  activated_at?: string | null;
  activated_by?: string | null;
}

export interface RegimeModelRevision {
  name: string;
  version: number;
  description?: string;
  config: RegimeModelConfig;
  status?: string | null;
  config_hash?: string | null;
  published_at?: string | null;
  created_at?: string | null;
  activated_at?: string | null;
  activated_by?: string | null;
}

export interface RegimeModelDetailResponse {
  model: RegimeModelSummary;
  activeRevision?: RegimeModelRevision | null;
  revisions: RegimeModelRevision[];
  latest?: RegimeSnapshot | null;
}

export interface UiRuntimeConfig {
  apiBaseUrl: string;
  oidcEnabled: boolean;
  authRequired: boolean;
  oidcAuthority?: string | null;
  oidcClientId?: string | null;
  oidcScopes: string[];
  oidcRedirectUri?: string | null;
  oidcPostLogoutRedirectUri?: string | null;
  oidcAudience: string[];
}

export interface AuthSessionStatus {
  authMode: string;
  subject: string;
  displayName?: string | null;
  username?: string | null;
  requiredRoles: string[];
  grantedRoles: string[];
}

export interface RunRecordResponse {
  run_id: string;
  status: RunStatus;
  submitted_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  run_name?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  error?: string | null;
  strategy_name?: string | null;
  strategy_version?: number | null;
  bar_size?: string | null;
  execution_name?: string | null;
}

export interface RunListResponse {
  runs: RunRecordResponse[];
  limit: number;
  offset: number;
}

export interface RunPinsResponse {
  strategyName?: string | null;
  strategyVersion?: number | null;
  rankingSchemaName?: string | null;
  rankingSchemaVersion?: number | null;
  universeName?: string | null;
  universeVersion?: number | null;
  regimeModelName?: string | null;
  regimeModelVersion?: number | null;
}

export interface RunStatusResponse {
  run_id: string;
  status: RunStatus;
  submitted_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  run_name?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  error?: string | null;
  strategy_name?: string | null;
  strategy_version?: number | null;
  bar_size?: string | null;
  execution_name?: string | null;
  results_ready_at?: string | null;
  results_schema_version?: number | null;
  pins?: RunPinsResponse | null;
}

export interface StrategyReferenceInput {
  strategyName: string;
  strategyVersion?: number | null;
}

export interface BacktestResultLinks {
  summaryUrl: string;
  metricsTimeseriesUrl: string;
  metricsRollingUrl: string;
  tradesUrl: string;
  closedPositionsUrl: string;
}

export interface BacktestLookupRequest {
  strategyRef?: StrategyReferenceInput | null;
  strategyConfig?: StrategyConfig | null;
  startTs: string;
  endTs: string;
  barSize: string;
  runName?: string | null;
}

export interface BacktestLookupResponse {
  found: boolean;
  state: BacktestLookupState;
  run?: RunStatusResponse | null;
  result?: BacktestSummary | null;
  links?: BacktestResultLinks | null;
}

export interface BacktestRunRequest {
  strategyRef?: StrategyReferenceInput | null;
  strategyConfig?: StrategyConfig | null;
  startTs: string;
  endTs: string;
  barSize: string;
  runName?: string | null;
}

export interface BacktestRunResponse {
  run: RunStatusResponse;
  created: boolean;
  reusedInflight: boolean;
  streamUrl: string;
}

export interface BacktestSummary {
  run_id?: string | null;
  run_name?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  total_return?: number | null;
  annualized_return?: number | null;
  annualized_volatility?: number | null;
  sharpe_ratio?: number | null;
  max_drawdown?: number | null;
  trades?: number | null;
  initial_cash?: number | null;
  final_equity?: number | null;
  gross_total_return?: number | null;
  gross_annualized_return?: number | null;
  total_commission?: number | null;
  total_slippage_cost?: number | null;
  total_transaction_cost?: number | null;
  cost_drag_bps?: number | null;
  avg_gross_exposure?: number | null;
  avg_net_exposure?: number | null;
  sortino_ratio?: number | null;
  calmar_ratio?: number | null;
  closed_positions?: number | null;
  winning_positions?: number | null;
  losing_positions?: number | null;
  hit_rate?: number | null;
  avg_win_pnl?: number | null;
  avg_loss_pnl?: number | null;
  avg_win_return?: number | null;
  avg_loss_return?: number | null;
  payoff_ratio?: number | null;
  profit_factor?: number | null;
  expectancy_pnl?: number | null;
  expectancy_return?: number | null;
  [key: string]: unknown;
}

export interface BacktestResultMetadata {
  results_schema_version: number;
  bar_size: string;
  periods_per_year: number;
  strategy_scope: string;
}

export interface BacktestStreamEvent {
  event: BacktestStreamEventType;
  run: RunStatusResponse;
  summary?: BacktestSummary | null;
  metadata?: BacktestResultMetadata | null;
  links?: BacktestResultLinks | null;
}

export interface TimeseriesPointResponse {
  date: string;
  portfolio_value: number;
  drawdown: number;
  period_return?: number | null;
  /** @deprecated Use period_return. */
  daily_return?: number | null;
  cumulative_return?: number | null;
  cash?: number | null;
  gross_exposure?: number | null;
  net_exposure?: number | null;
  turnover?: number | null;
  commission?: number | null;
  slippage_cost?: number | null;
  trade_count?: number | null;
}

export interface TimeseriesResponse {
  metadata?: BacktestResultMetadata | null;
  points: TimeseriesPointResponse[];
  total_points: number;
  truncated: boolean;
}

export interface RollingMetricPointResponse {
  date: string;
  window_periods?: number | null;
  /** @deprecated Use window_periods. */
  window_days?: number | null;
  rolling_return?: number | null;
  rolling_volatility?: number | null;
  rolling_sharpe?: number | null;
  rolling_max_drawdown?: number | null;
  turnover_sum?: number | null;
  commission_sum?: number | null;
  slippage_cost_sum?: number | null;
  n_trades_sum?: number | null;
  gross_exposure_avg?: number | null;
  net_exposure_avg?: number | null;
}

export interface RollingMetricsResponse {
  metadata?: BacktestResultMetadata | null;
  points: RollingMetricPointResponse[];
  total_points: number;
  truncated: boolean;
}

export interface TradeResponse {
  execution_date: string;
  symbol: string;
  quantity: number;
  price: number;
  notional: number;
  commission: number;
  slippage_cost: number;
  cash_after: number;
  position_id?: string | null;
  trade_role?: TradeRole | null;
}

export interface TradeListResponse {
  trades: TradeResponse[];
  total: number;
  limit: number;
  offset: number;
}

export interface ClosedPositionResponse {
  position_id: string;
  symbol: string;
  opened_at: string;
  closed_at: string;
  holding_period_bars: number;
  average_cost: number;
  exit_price: number;
  max_quantity: number;
  resize_count: number;
  realized_pnl: number;
  realized_return?: number | null;
  total_commission: number;
  total_slippage_cost: number;
  total_transaction_cost: number;
  exit_reason?: string | null;
  exit_rule_id?: string | null;
}

export interface ClosedPositionListResponse {
  positions: ClosedPositionResponse[];
  total: number;
  limit: number;
  offset: number;
}

export interface BacktestClaimRequest {
  executionName?: string | null;
}

export interface BacktestStartRequest {
  executionName?: string | null;
}

export interface BacktestCompleteRequest {
  summary: Record<string, unknown>;
}

export interface BacktestFailRequest {
  error: string;
}

export interface BacktestReconcileResponse {
  dispatchedCount: number;
  dispatchFailedCount: number;
  failedStaleRunningCount: number;
  skippedActiveCount: number;
  noActionCount: number;
  dispatchedRunIds: string[];
  dispatchFailedRunIds: string[];
  failedRunIds: string[];
}
