// Generated by python/scripts/export_schemas.py.
// Do not edit by hand.

export type AuthSessionMode = 'bearer' | 'cookie';
export type AuthProvider = 'disabled' | 'oidc' | 'password';
export type JobCategory = 'data-pipeline' | 'strategy-compute' | 'operational-support';
export type JobMetadataSource = 'tags' | 'legacy-catalog' | 'unknown';
export type JobMetadataStatus = 'valid' | 'fallback' | 'invalid';
export type PublicationReconcileStatus = 'pending' | 'processed' | 'error';
export type ExitRuleType = 'stop_loss_fixed' | 'take_profit_fixed' | 'trailing_stop_pct' | 'trailing_stop_atr' | 'time_stop' | 'rank_decay';
export type ExitRuleScope = 'position';
export type ExitRuleAction = 'exit_full';
export type ExitRulePriceField = 'open' | 'high' | 'low' | 'close';
export type ExitRuleReference = 'entry_price' | 'highest_since_entry';
export type IntrabarConflictPolicy = 'stop_first' | 'take_profit_first' | 'priority_order';
export type StrategyPositionSizeMode = 'pct_of_allocatable_capital' | 'notional_base_ccy';
export type StrategyPositionAssetClass = 'equity' | 'option';
export type RiskTolerancePreset = 'conservative' | 'balanced' | 'aggressive';
export type RebalanceFrequency = 'every_bar' | 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'every_n_bars' | 'manual';
export type RebalanceExecutionTiming = 'next_bar_open';
export type ReusableConfigStatus = 'draft' | 'active' | 'deprecated';
export type ReusableConfigIntendedUse = 'research' | 'validation' | 'production_candidate';
export type ReusableRebalanceCadence = 'monthly' | 'quarterly';
export type ReusableRebalanceDayRule = 'first_trading_day' | 'last_trading_day';
export type ReusableRebalanceAnchor = 'close' | 'next_open';
export type StrategyRiskPolicyScope = 'strategy' | 'sleeve';
export type StrategyRiskStopLossBasis = 'strategy_nav_drawdown' | 'sleeve_nav_drawdown';
export type StrategyRiskTakeProfitBasis = 'strategy_nav_gain' | 'sleeve_nav_gain';
export type StrategyRiskStopLossAction = 'reduce_exposure' | 'liquidate' | 'freeze_buys';
export type StrategyRiskTakeProfitAction = 'reduce_exposure' | 'rebalance_to_target';
export type RegimeCode = 'trending_up' | 'trending_down' | 'mean_reverting' | 'low_volatility' | 'high_volatility' | 'liquidity_stress' | 'macro_alignment' | 'unclassified';
export type UniverseSource = 'postgres_gold';
export type UniverseGroupOperator = 'and' | 'or';
export type UniverseConditionOperator = 'eq' | 'ne' | 'gt' | 'gte' | 'lt' | 'lte' | 'in' | 'not_in' | 'is_null' | 'is_not_null';
export type UniverseFieldId = 'market.close' | 'security.is_active' | 'security.sector' | 'security.delisted_at' | 'market.trade_date' | 'market.timestamp' | 'returns.return_20d' | 'returns.return_126d' | 'quality.piotroski_f_score' | 'earnings.surprise_pct' | 'security.market_cap' | 'market.dollar_volume_20d' | 'security.primary_listing' | 'security.country' | 'security.is_price_liquidity_eligible';
export type UniverseValue = string | number | boolean;
export type UniverseValueKind = 'string' | 'number' | 'boolean' | 'date' | 'datetime';
export type RankingTransformType = 'percentile_rank' | 'zscore' | 'minmax' | 'clip' | 'winsorize' | 'coalesce' | 'log1p' | 'negate' | 'abs';
export type RankingDirection = 'asc' | 'desc';
export type RankingMissingValuePolicy = 'exclude' | 'zero';
export type RegimeSignalState = 'active' | 'inactive' | 'insufficient_data';
export type RegimeTransitionType = 'entered' | 'exited';
export type RegimePolicyMode = 'observe_only';
export type TrendState = 'positive' | 'negative' | 'near_zero';
export type CurveState = 'contango' | 'flat' | 'inverted';
export type RunStatus = 'queued' | 'running' | 'completed' | 'failed';
export type BrokerVendor = 'alpaca' | 'schwab' | 'etrade';
export type BrokerHealthTone = 'healthy' | 'warning' | 'critical';
export type BrokerConnectionState = 'connected' | 'degraded' | 'disconnected' | 'reconnect_required';
export type BrokerAuthStatus = 'authenticated' | 'expires_soon' | 'expired' | 'reauth_required' | 'not_connected';
export type BrokerSyncStatus = 'fresh' | 'stale' | 'syncing' | 'paused' | 'failed' | 'never_synced';
export type BrokerTradeReadiness = 'ready' | 'review' | 'blocked';
export type BrokerAccountType = 'cash' | 'margin' | 'retirement' | 'paper' | 'other';
export type BrokerAlertSeverity = 'info' | 'warning' | 'critical';
export type BrokerAlertStatus = 'open' | 'acknowledged' | 'resolved';
export type BrokerSyncTrigger = 'scheduled' | 'manual' | 'reconnect' | 'backfill';
export type BrokerSyncScope = 'balances' | 'positions' | 'orders' | 'full';
export type BrokerSyncRunStatus = 'queued' | 'running' | 'completed' | 'failed';
export type BrokerPolicySide = 'long' | 'short';
export type BrokerPolicyAssetClass = 'equity' | 'option';
export type BrokerPositionSizeMode = 'pct_of_allocatable_capital' | 'notional_base_ccy';
export type BrokerAllocationMode = 'percent' | 'notional_base_ccy';
export type BrokerConfigurationAuditCategory = 'trading_policy' | 'allocation' | 'onboarding';
export type BrokerConfigurationAuditOutcome = 'saved' | 'denied' | 'warning';
export type BrokerAccountExecutionPosture = 'monitor_only' | 'paper' | 'sandbox' | 'live';
export type BrokerAccountOnboardingCandidateState = 'available' | 'already_configured' | 'disabled' | 'blocked' | 'unavailable';
export type BrokerAccountOnboardingDiscoveryStatus = 'completed' | 'provider_unavailable' | 'not_connected' | 'failed';
export type BrokerAccountActionType = 'reconnect' | 'pause_sync' | 'resume_sync' | 'refresh' | 'acknowledge_alert' | 'update_trading_policy' | 'update_allocation';
export type BrokerAccountActionStatus = 'accepted' | 'in_progress' | 'completed' | 'failed';
export type TradeProvider = 'alpaca' | 'etrade' | 'schwab';
export type TradeEnvironment = 'paper' | 'sandbox' | 'live';
export type TradeReadiness = 'ready' | 'review' | 'blocked';
export type TradeAssetClass = 'equity' | 'etf' | 'option' | 'crypto' | 'mutual_fund' | 'unknown';
export type TradeOrderSide = 'buy' | 'sell';
export type TradeOrderType = 'market' | 'limit' | 'stop' | 'stop_limit';
export type TradeTimeInForce = 'day' | 'gtc' | 'opg' | 'cls' | 'ioc' | 'fok';
export type TradeOrderStatus = 'draft' | 'previewed' | 'submitted' | 'accepted' | 'partially_filled' | 'filled' | 'cancel_pending' | 'cancelled' | 'rejected' | 'expired' | 'unknown_reconcile_required';
export type TradeRiskCheckStatus = 'pass' | 'warning' | 'fail';
export type TradeAuditEventType = 'preview' | 'submit' | 'cancel' | 'status_update' | 'reject' | 'fill' | 'reconcile' | 'system_block' | 'authz_block';
export type TradeDataFreshnessState = 'fresh' | 'stale' | 'unknown';
export type TradeAuditSeverity = 'info' | 'warning' | 'critical';
export type TradeBlotterEventType = 'fill' | 'cancel' | 'fee' | 'cash_adjustment' | 'dividend' | 'interest' | 'journal';
export type NotificationKind = 'message' | 'trade_approval';
export type NotificationDeliveryChannel = 'email' | 'sms';
export type NotificationDeliveryStatus = 'pending' | 'sent' | 'failed' | 'skipped';
export type NotificationDecision = 'approve' | 'deny';
export type NotificationDecisionStatus = 'not_required' | 'pending' | 'approved' | 'denied' | 'expired';
export type NotificationExecutionStatus = 'not_applicable' | 'pending_approval' | 'submitted' | 'blocked' | 'release_failed';
export type NotificationRequestStatus = 'pending' | 'delivered' | 'delivery_failed' | 'decided' | 'expired';
export type IntradayWatchlistSymbolAppendRunSkippedReason = 'watchlist_disabled' | 'no_new_symbols' | 'queue_run_disabled';
export type PortfolioAllocationMode = 'percent' | 'notional_base_ccy';
export type BacktestLookupState = 'not_run' | 'queued' | 'running' | 'completed' | 'failed';
export type BacktestStreamEventType = 'accepted' | 'status' | 'heartbeat' | 'completed' | 'failed';
export type TradeRole = 'entry' | 'rebalance_increase' | 'rebalance_decrease' | 'exit';
export type BacktestPolicyEventScope = 'strategy' | 'sleeve' | 'position' | 'symbol' | 'portfolio';
export type BacktestPolicyEventType = 'rebalance' | 'strategy_risk' | 'position_exit' | 'reentry';
export type BacktestPolicyDecision = 'applied' | 'skipped' | 'blocked';
export type BacktestResearchIntegrityStatus = 'strict_passed' | 'strict_failed' | 'legacy_uncontrolled';
export type BacktestExecutionModel = 'simple_bps';
export type BacktestExecutionModelQuality = 'not_tca_grade';
export type BacktestApprovalReadiness = 'research_only';
export type BacktestDataQualityEventSeverity = 'warning' | 'error' | 'fatal';
export type AiChatStreamEvent = AiChatStartedEvent | AiChatStatusEvent | AiChatReasoningSummaryDeltaEvent | AiChatOutputTextDeltaEvent | AiChatCompletedEvent | AiChatErrorEvent;
export type UniverseNode = UniverseGroup | UniverseCondition;

export interface StrategyConfig {
  componentRefs?: StrategyComponentRefs | null;
  universeConfigName?: string | null;
  universeConfigVersion?: number | null;
  universe?: UniverseDefinition | null;
  rebalance: string;
  longOnly: boolean;
  topN: number;
  lookbackWindow: number;
  holdingPeriod: number;
  costModel: string;
  rankingSchemaName?: string | null;
  rankingSchemaVersion?: number | null;
  regimePolicyConfigName?: string | null;
  regimePolicyConfigVersion?: number | null;
  regimePolicy?: RegimePolicy | null;
  riskProfileName?: string | null;
  riskPolicyName?: string | null;
  riskPolicyVersion?: number | null;
  positionPolicy?: StrategyPositionPolicy | null;
  rebalancePolicy?: RebalancePolicy | null;
  strategyRiskPolicy?: StrategyRiskPolicy | null;
  exitRuleSetName?: string | null;
  exitRuleSetVersion?: number | null;
  intrabarConflictPolicy: IntrabarConflictPolicy;
  exits: ExitRule[];
}

export interface StrategyComponentRefs {
  universe?: ConfigReference | null;
  ranking?: ConfigReference | null;
  rebalance?: ConfigReference | null;
  regimePolicy?: ConfigReference | null;
  riskPolicy?: ConfigReference | null;
  exitPolicy?: ConfigReference | null;
}

export interface ConfigReference {
  name: string;
  version: number;
}

export interface UniverseDefinition {
  source: UniverseSource;
  root: UniverseGroup;
}

export interface UniverseGroup {
  kind: 'group';
  operator: UniverseGroupOperator;
  clauses: UniverseNode[];
}

export interface UniverseCondition {
  kind: 'condition';
  field: UniverseFieldId;
  operator: UniverseConditionOperator;
  value?: string | number | boolean | null;
  values?: UniverseValue[] | null;
}

export interface RegimePolicy {
  modelName: string;
  modelVersion?: number | null;
  mode: RegimePolicyMode;
}

export interface StrategyPositionPolicy {
  targetPositionSize?: StrategyPositionSizeLimit | null;
  maxPositionSize?: StrategyPositionSizeLimit | null;
  maxOpenPositions?: number | null;
  allowedAssetClasses: StrategyPositionAssetClass[];
  requireOrderConfirmation: boolean;
}

export interface StrategyPositionSizeLimit {
  mode: StrategyPositionSizeMode;
  value: number;
}

export interface RebalancePolicy {
  frequency: RebalanceFrequency;
  executionTiming: RebalanceExecutionTiming;
  cadence?: ReusableRebalanceCadence | null;
  dayRule?: ReusableRebalanceDayRule | null;
  anchor?: ReusableRebalanceAnchor | null;
  tradeDelayBars: number;
  driftThresholdBps?: number | null;
  maxTurnoverPerRebalance?: number | null;
  intervalBars?: number | null;
  driftThresholdPct?: number | null;
  minTradeNotional: number;
  cashBufferPct: number;
  maxTurnoverPct?: number | null;
  allowPartialRebalance: boolean;
  closeRemovedPositions: boolean;
}

export interface StrategyRiskPolicy {
  enabled: boolean;
  scope: StrategyRiskPolicyScope;
  stopLoss?: StrategyRiskStopLossPolicy | null;
  takeProfit?: StrategyRiskTakeProfitPolicy | null;
  reentry: StrategyRiskReentryPolicy;
}

export interface StrategyRiskStopLossPolicy {
  id: string;
  enabled: boolean;
  basis: StrategyRiskStopLossBasis;
  thresholdPct: number;
  action: StrategyRiskStopLossAction;
  reductionPct?: number | null;
}

export interface StrategyRiskTakeProfitPolicy {
  id: string;
  enabled: boolean;
  basis: StrategyRiskTakeProfitBasis;
  thresholdPct: number;
  action: StrategyRiskTakeProfitAction;
  reductionPct?: number | null;
}

export interface StrategyRiskReentryPolicy {
  cooldownBars: number;
  requireApproval: boolean;
}

export interface ExitRule {
  id: string;
  type: ExitRuleType;
  scope: ExitRuleScope;
  priceField?: ExitRulePriceField | null;
  value?: number | null;
  atrColumn?: string | null;
  priority?: number | null;
  action: ExitRuleAction;
  minHoldBars: number;
  reference?: ExitRuleReference | null;
  rankThreshold?: number | null;
}

export interface ConfigIdentity {
  name: string;
  version: number;
  status: ReusableConfigStatus;
  description: string;
  intendedUse: ReusableConfigIntendedUse;
  thesis: string;
  whatToMonitor: string[];
}

export interface ConfigRevisionReference {
  name: string;
  version: number;
}

export interface UniverseConfigPreset {
  identity: ConfigIdentity;
  config: UniverseDefinition;
}

export interface RankingSchemaPreset {
  identity: ConfigIdentity;
  config: RankingSchemaConfig;
}

export interface RankingSchemaConfig {
  universeConfigName?: string | null;
  groups: RankingGroup[];
  overallTransforms: RankingTransform[];
}

export interface RankingGroup {
  name: string;
  weight: number;
  factors: RankingFactor[];
  transforms: RankingTransform[];
}

export interface RankingFactor {
  name: string;
  table: string;
  column: string;
  weight: number;
  direction: RankingDirection;
  missingValuePolicy: RankingMissingValuePolicy;
  transforms: RankingTransform[];
}

export interface RankingTransform {
  type: RankingTransformType;
  params: Record<string, string | number | boolean | null>;
}

export interface RebalancePolicyPreset {
  identity: ConfigIdentity;
  config: RebalancePolicy;
}

export interface RegimePolicyPreset {
  identity: ConfigIdentity;
  config: RegimePolicy;
}

export interface StrategyRiskPolicyPreset {
  identity: ConfigIdentity;
  config: StrategyRiskPolicy;
}

export interface ExitPolicyPreset {
  identity: ConfigIdentity;
  config: ExitRuleSetConfig;
}

export interface ExitRuleSetConfig {
  intrabarConflictPolicy: IntrabarConflictPolicy;
  exits: ExitRule[];
}

export interface RiskPolicyConfig {
  policy: StrategyRiskPolicy;
}

export interface RiskPolicyConfigSummary {
  name: string;
  description: string;
  version: number;
  archived: boolean;
  usageCount: number;
  updatedAt?: string | null;
}

export interface RiskPolicyConfigRevision {
  name: string;
  version: number;
  description: string;
  config: RiskPolicyConfig;
  configHash?: string | null;
  createdAt?: string | null;
  createdBy?: string | null;
}

export interface RiskPolicyConfigDetailResponse {
  policy: RiskPolicyConfigSummary;
  activeRevision?: RiskPolicyConfigRevision | null;
  revisions: RiskPolicyConfigRevision[];
}

export interface RiskPolicyConfigUpsertRequest {
  name: string;
  description: string;
  config: RiskPolicyConfig;
}

export interface ExitRuleSetSummary {
  name: string;
  description: string;
  version: number;
  archived: boolean;
  usageCount: number;
  ruleCount: number;
  updatedAt?: string | null;
}

export interface ExitRuleSetRevision {
  name: string;
  version: number;
  description: string;
  config: ExitRuleSetConfig;
  configHash?: string | null;
  createdAt?: string | null;
  createdBy?: string | null;
}

export interface ExitRuleSetDetailResponse {
  ruleSet: ExitRuleSetSummary;
  activeRevision?: ExitRuleSetRevision | null;
  revisions: ExitRuleSetRevision[];
}

export interface ExitRuleSetUpsertRequest {
  name: string;
  description: string;
  config: ExitRuleSetConfig;
}

export interface StrategyRiskProfileConfig {
  presetClass: RiskTolerancePreset;
  positionPolicy: StrategyPositionPolicy;
}

export interface StrategyRiskProfileSummary {
  name: string;
  description: string;
  presetClass: RiskTolerancePreset;
  version: number;
  isSystem: boolean;
  usageCount: number;
  updatedAt?: string | null;
}

export interface StrategyRiskProfileDetail {
  name: string;
  description: string;
  presetClass: RiskTolerancePreset;
  version: number;
  isSystem: boolean;
  usageCount: number;
  updatedAt?: string | null;
  config: StrategyRiskProfileConfig;
}

export interface UniverseCatalogResponse {
  source: UniverseSource;
  fields: UniverseFieldDefinition[];
}

export interface UniverseFieldDefinition {
  id: UniverseFieldId;
  label: string;
  valueKind: UniverseValueKind;
  operators: UniverseConditionOperator[];
}

export interface UniversePreviewResponse {
  source: UniverseSource;
  symbolCount: number;
  sampleSymbols: string[];
  fieldsUsed: UniverseFieldId[];
  warnings: string[];
}

export interface RegimePolicyConfig {
  modelName: string;
  modelVersion?: number | null;
  mode: RegimePolicyMode;
}

export interface RegimePolicyConfigSummary {
  name: string;
  description: string;
  version: number;
  archived: boolean;
  usageCount: number;
  modelName: string;
  modelVersion?: number | null;
  mode: RegimePolicyMode;
  updatedAt?: string | null;
}

export interface RegimePolicyConfigRevision {
  name: string;
  version: number;
  description: string;
  config: RegimePolicyConfig;
  configHash?: string | null;
  createdAt?: string | null;
  createdBy?: string | null;
}

export interface RegimePolicyConfigDetailResponse {
  policy: RegimePolicyConfigSummary;
  activeRevision?: RegimePolicyConfigRevision | null;
  revisions: RegimePolicyConfigRevision[];
}

export interface RegimePolicyConfigUpsertRequest {
  name: string;
  description: string;
  config: RegimePolicyConfig;
}

export interface RegimeModelConfig {
  activationThreshold: number;
  signalConfigs: Record<string, RegimeSignalConfig>;
  haltVixThreshold: number;
  haltVixStreakDays: number;
}

export interface RegimeSignalConfig {
  displayName: string;
  requiredMetrics: string[];
  rules: RegimeMetricRule[];
}

export interface RegimeMetricRule {
  metric: string;
  comparison: 'gte' | 'lte' | 'between' | 'bool_true';
  lower?: number | null;
  upper?: number | null;
  description: string;
}

export interface RegimeSnapshot {
  as_of_date: string;
  effective_from_date: string;
  model_name: string;
  model_version: number;
  signals: RegimeSignal[];
  active_regimes: RegimeCode[];
  halt_flag: boolean;
  halt_reason?: string | null;
  computed_at?: string | null;
}

export interface RegimeSignal {
  regime_code: RegimeCode;
  display_name: string;
  signal_state: RegimeSignalState;
  score: number;
  activation_threshold: number;
  is_active: boolean;
  matched_rule_id?: string | null;
  evidence: Record<string, unknown>;
}

export interface RegimeInputRow {
  as_of_date: string;
  metric_values: Record<string, unknown>;
  inputs_complete_flag: boolean;
  computed_at?: string | null;
}

export interface RegimeTransitionRow {
  model_name: string;
  model_version: number;
  effective_from_date: string;
  regime_code: RegimeCode;
  transition_type: RegimeTransitionType;
  prior_score?: number | null;
  new_score?: number | null;
  activation_threshold: number;
  trigger_rule_id?: string | null;
  computed_at?: string | null;
}

export interface RegimeModelSummary {
  name: string;
  description?: string;
  version: number;
  updated_at?: string | null;
  active_version?: number | null;
  activated_at?: string | null;
  activated_by?: string | null;
}

export interface RegimeModelRevision {
  name: string;
  version: number;
  description?: string;
  config: RegimeModelConfig;
  status?: string | null;
  config_hash?: string | null;
  published_at?: string | null;
  created_at?: string | null;
  activated_at?: string | null;
  activated_by?: string | null;
}

export interface RegimeModelDetailResponse {
  model: RegimeModelSummary;
  activeRevision?: RegimeModelRevision | null;
  revisions: RegimeModelRevision[];
  latest?: RegimeSnapshot | null;
}

export interface UiRuntimeConfig {
  apiBaseUrl: string;
  authSessionMode: AuthSessionMode;
  authProvider: AuthProvider;
  oidcEnabled: boolean;
  authRequired: boolean;
  oidcAuthority?: string | null;
  oidcClientId?: string | null;
  oidcScopes: string[];
  oidcRedirectUri?: string | null;
  oidcPostLogoutRedirectUri?: string | null;
  oidcAudience: string[];
}

export interface AuthSessionStatus {
  authMode: string;
  subject: string;
  displayName?: string | null;
  username?: string | null;
  requiredRoles: string[];
  grantedRoles: string[];
}

export interface PasswordAuthSessionRequest {
  password: string;
}

export interface RuntimeJobMetadata {
  jobCategory: JobCategory;
  jobKey: string;
  jobRole: string;
  triggerOwner: string;
  metadataSource: JobMetadataSource;
  metadataStatus: JobMetadataStatus;
}

export interface ResultsReconcileRequest {
  dryRun: boolean;
}

export interface ResultsReconcileResponse {
  dryRun: boolean;
  rankingDirtyCount: number;
  rankingNoopCount: number;
  canonicalEnqueuedCount: number;
  canonicalUpToDateCount: number;
  canonicalSkippedCount: number;
  publicationSignalsProcessedCount: number;
  publicationSignalsErrorCount: number;
  errorCount: number;
  errors: string[];
}

export interface StrategyPublicationReconcileSignalRequest {
  jobKey: string;
  sourceFingerprint: string;
  publishedAt?: string | null;
  metadata: RegimePublicationReconcileMetadata;
}

export interface RegimePublicationReconcileMetadata {
  publishedAsOfDate: string;
  inputAsOfDate?: string | null;
  historyRows: number;
  latestRows: number;
  transitionRows: number;
  activeModels: RegimePublicationModelReference[];
  domainArtifactPath?: string | null;
  producerJobName: string;
}

export interface RegimePublicationModelReference {
  modelName: string;
  modelVersion: number;
}

export interface StrategyPublicationReconcileSignalResponse {
  jobKey: string;
  sourceFingerprint: string;
  status: PublicationReconcileStatus;
  created: boolean;
  createdAt: string;
  updatedAt: string;
  processedAt?: string | null;
  error?: string | null;
}

export interface RunRecordResponse {
  run_id: string;
  status: BrokerSyncRunStatus;
  submitted_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  run_name?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  error?: string | null;
  strategy_name?: string | null;
  strategy_version?: number | null;
  bar_size?: string | null;
  execution_name?: string | null;
}

export interface RunListResponse {
  runs: RunRecordResponse[];
  limit: number;
  offset: number;
}

export interface BacktestLookupRequest {
  strategyRef?: StrategyReferenceInput | null;
  strategyConfig?: StrategyConfig | null;
  startTs: string;
  endTs: string;
  barSize: string;
  runName?: string | null;
}

export interface StrategyReferenceInput {
  strategyName: string;
  strategyVersion?: number | null;
}

export interface BacktestLookupResponse {
  found: boolean;
  state: BacktestLookupState;
  run?: RunStatusResponse | null;
  result?: BacktestSummary | null;
  links?: BacktestResultLinks | null;
}

export interface RunStatusResponse {
  run_id: string;
  status: BrokerSyncRunStatus;
  submitted_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  run_name?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  error?: string | null;
  strategy_name?: string | null;
  strategy_version?: number | null;
  bar_size?: string | null;
  execution_name?: string | null;
  results_ready_at?: string | null;
  results_schema_version?: number | null;
  pins?: RunPinsResponse | null;
}

export interface RunPinsResponse {
  strategyName?: string | null;
  strategyVersion?: number | null;
  rankingSchemaName?: string | null;
  rankingSchemaVersion?: number | null;
  universeName?: string | null;
  universeVersion?: number | null;
  regimeModelName?: string | null;
  regimeModelVersion?: number | null;
}

export interface BacktestSummary {
  run_id?: string | null;
  run_name?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  total_return?: number | null;
  annualized_return?: number | null;
  annualized_volatility?: number | null;
  sharpe_ratio?: number | null;
  max_drawdown?: number | null;
  trades?: number | null;
  initial_cash?: number | null;
  final_equity?: number | null;
  gross_total_return?: number | null;
  gross_annualized_return?: number | null;
  total_commission?: number | null;
  total_slippage_cost?: number | null;
  total_transaction_cost?: number | null;
  cost_drag_bps?: number | null;
  avg_gross_exposure?: number | null;
  avg_net_exposure?: number | null;
  sortino_ratio?: number | null;
  calmar_ratio?: number | null;
  closed_positions?: number | null;
  winning_positions?: number | null;
  losing_positions?: number | null;
  hit_rate?: number | null;
  avg_win_pnl?: number | null;
  avg_loss_pnl?: number | null;
  avg_win_return?: number | null;
  avg_loss_return?: number | null;
  payoff_ratio?: number | null;
  profit_factor?: number | null;
  expectancy_pnl?: number | null;
  expectancy_return?: number | null;
  research_integrity_status?: BacktestResearchIntegrityStatus | null;
  execution_model?: BacktestExecutionModel | null;
  execution_model_quality?: BacktestExecutionModelQuality | null;
  approval_readiness?: BacktestApprovalReadiness | null;
  data_quality_event_count?: number | null;
  policy_event_count?: number | null;
  [key: string]: unknown;
}

export interface BacktestResultLinks {
  summaryUrl: string;
  metricsTimeseriesUrl: string;
  metricsRollingUrl: string;
  tradesUrl: string;
  closedPositionsUrl: string;
}

export interface BacktestRunRequest {
  strategyRef?: StrategyReferenceInput | null;
  strategyConfig?: StrategyConfig | null;
  startTs: string;
  endTs: string;
  barSize: string;
  runName?: string | null;
}

export interface BacktestRunResponse {
  run: RunStatusResponse;
  created: boolean;
  reusedInflight: boolean;
  streamUrl: string;
}

export interface BacktestStreamEvent {
  event: BacktestStreamEventType;
  run: RunStatusResponse;
  summary?: BacktestSummary | null;
  metadata?: BacktestResultMetadata | null;
  links?: BacktestResultLinks | null;
}

export interface BacktestResultMetadata {
  results_schema_version: number;
  bar_size: string;
  periods_per_year: number;
  strategy_scope: string;
}

export interface TimeseriesResponse {
  metadata?: BacktestResultMetadata | null;
  points: TimeseriesPointResponse[];
  total_points: number;
  truncated: boolean;
}

export interface TimeseriesPointResponse {
  date: string;
  portfolio_value: number;
  drawdown: number;
  period_return?: number | null;
  /** @deprecated Use period_return. */
  daily_return?: number | null;
  cumulative_return?: number | null;
  cash?: number | null;
  gross_exposure?: number | null;
  net_exposure?: number | null;
  turnover?: number | null;
  commission?: number | null;
  slippage_cost?: number | null;
  trade_count?: number | null;
}

export interface RollingMetricsResponse {
  metadata?: BacktestResultMetadata | null;
  points: RollingMetricPointResponse[];
  total_points: number;
  truncated: boolean;
}

export interface RollingMetricPointResponse {
  date: string;
  window_periods?: number | null;
  /** @deprecated Use window_periods. */
  window_days?: number | null;
  rolling_return?: number | null;
  rolling_volatility?: number | null;
  rolling_sharpe?: number | null;
  rolling_max_drawdown?: number | null;
  turnover_sum?: number | null;
  commission_sum?: number | null;
  slippage_cost_sum?: number | null;
  n_trades_sum?: number | null;
  gross_exposure_avg?: number | null;
  net_exposure_avg?: number | null;
}

export interface TradeListResponse {
  trades: TradeResponse[];
  total: number;
  limit: number;
  offset: number;
}

export interface TradeResponse {
  execution_date: string;
  symbol: string;
  quantity: number;
  price: number;
  notional: number;
  commission: number;
  slippage_cost: number;
  cash_after: number;
  position_id?: string | null;
  trade_role?: TradeRole | null;
}

export interface ClosedPositionListResponse {
  positions: ClosedPositionResponse[];
  total: number;
  limit: number;
  offset: number;
}

export interface ClosedPositionResponse {
  position_id: string;
  symbol: string;
  opened_at: string;
  closed_at: string;
  holding_period_bars: number;
  average_cost: number;
  exit_price: number;
  max_quantity: number;
  resize_count: number;
  realized_pnl: number;
  realized_return?: number | null;
  total_commission: number;
  total_slippage_cost: number;
  total_transaction_cost: number;
  exit_reason?: string | null;
  exit_rule_id?: string | null;
}

export interface BacktestPolicyEventListResponse {
  events: BacktestPolicyEvent[];
  total: number;
  limit: number;
  offset: number;
}

export interface BacktestPolicyEvent {
  run_id: string;
  event_seq: number;
  bar_ts: string;
  scope: BacktestPolicyEventScope;
  policy_type: BacktestPolicyEventType;
  decision: BacktestPolicyDecision;
  reason_code: string;
  symbol?: string | null;
  position_id?: string | null;
  policy_id?: string | null;
  observed_value?: number | null;
  threshold_value?: number | null;
  action?: string | null;
  details: Record<string, unknown>;
}

export interface BacktestDataQualityEventListResponse {
  events: BacktestDataQualityEvent[];
  total: number;
  limit: number;
  offset: number;
}

export interface BacktestDataQualityEvent {
  run_id: string;
  event_seq: number;
  bar_ts: string;
  severity: BacktestDataQualityEventSeverity;
  table_name: string;
  symbol?: string | null;
  field_name?: string | null;
  reason_code: string;
  action: string;
  details: Record<string, unknown>;
}

export interface BacktestClaimRequest {
  executionName?: string | null;
}

export interface BacktestStartRequest {
  executionName?: string | null;
}

export interface BacktestCompleteRequest {
  summary: Record<string, unknown>;
}

export interface BacktestFailRequest {
  error: string;
}

export interface BacktestReconcileResponse {
  dispatchedCount: number;
  dispatchFailedCount: number;
  failedStaleRunningCount: number;
  skippedActiveCount: number;
  noActionCount: number;
  dispatchedRunIds: string[];
  dispatchFailedRunIds: string[];
  failedRunIds: string[];
}

export interface BrokerAccountDetail {
  account: BrokerAccountSummary;
  capabilities: BrokerCapabilityFlags;
  accountType: BrokerAccountType;
  tradingBlocked: boolean;
  tradingBlockedReason?: string | null;
  unsettledFunds?: number | null;
  dayTradeBuyingPower?: number | null;
  maintenanceExcess?: number | null;
  alerts: BrokerAccountAlert[];
  syncRuns: BrokerSyncRun[];
  recentActivity: BrokerAccountActivity[];
  configuration?: BrokerAccountConfiguration | null;
}

export interface BrokerAccountSummary {
  accountId: string;
  broker: TradeProvider;
  name: string;
  accountNumberMasked?: string | null;
  baseCurrency: string;
  overallStatus: BrokerHealthTone;
  tradeReadiness: TradeReadiness;
  tradeReadinessReason?: string | null;
  highestAlertSeverity?: TradeAuditSeverity | null;
  connectionHealth: BrokerConnectionHealth;
  equity: number;
  cash: number;
  buyingPower: number;
  openPositionCount: number;
  openOrderCount: number;
  lastSyncedAt?: string | null;
  snapshotAsOf?: string | null;
  activePortfolioName?: string | null;
  strategyLabel?: string | null;
  configurationVersion?: number | null;
  allocationSummary?: BrokerStrategyAllocationSummary | null;
  alertCount: number;
}

export interface BrokerConnectionHealth {
  overallStatus: BrokerHealthTone;
  authStatus: BrokerAuthStatus;
  connectionState: BrokerConnectionState;
  syncStatus: BrokerSyncStatus;
  lastCheckedAt?: string | null;
  lastSuccessfulSyncAt?: string | null;
  lastFailedSyncAt?: string | null;
  authExpiresAt?: string | null;
  staleReason?: string | null;
  failureMessage?: string | null;
  syncPaused: boolean;
}

export interface BrokerStrategyAllocationSummary {
  portfolioName?: string | null;
  portfolioVersion?: number | null;
  allocationMode: PortfolioAllocationMode;
  allocatableCapital?: number | null;
  allocatedPercent?: number | null;
  allocatedNotionalBaseCcy?: number | null;
  remainingPercent?: number | null;
  remainingNotionalBaseCcy?: number | null;
  sharedActivePortfolio: boolean;
  effectiveFrom?: string | null;
  items: BrokerStrategyAllocationItem[];
}

export interface BrokerStrategyAllocationItem {
  sleeveId: string;
  sleeveName: string;
  strategy: BrokerStrategyReference;
  allocationMode: PortfolioAllocationMode;
  targetWeightPct?: number | null;
  targetNotionalBaseCcy?: number | null;
  derivedWeightPct?: number | null;
  enabled: boolean;
  notes: string;
}

export interface BrokerStrategyReference {
  strategyName: string;
  strategyVersion: number;
}

export interface BrokerCapabilityFlags {
  canReadBalances: boolean;
  canReadPositions: boolean;
  canReadOrders: boolean;
  canTrade: boolean;
  canReconnect: boolean;
  canPauseSync: boolean;
  canRefresh: boolean;
  canAcknowledgeAlerts: boolean;
  canReadTradingPolicy: boolean;
  canWriteTradingPolicy: boolean;
  canReadAllocation: boolean;
  canWriteAllocation: boolean;
  canReleaseTradeConfirmation: boolean;
  readOnlyReason?: string | null;
}

export interface BrokerAccountAlert {
  alertId: string;
  accountId: string;
  severity: TradeAuditSeverity;
  status: BrokerAlertStatus;
  code: string;
  title: string;
  message: string;
  observedAt: string;
  acknowledgedAt?: string | null;
  acknowledgedBy?: string | null;
  resolvedAt?: string | null;
  asOfDate?: string | null;
}

export interface BrokerSyncRun {
  runId: string;
  accountId: string;
  trigger: BrokerSyncTrigger;
  scope: BrokerSyncScope;
  status: BrokerSyncRunStatus;
  requestedAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  warningCount: number;
  rowsSynced?: number | null;
  summary?: string | null;
  errorMessage?: string | null;
}

export interface BrokerAccountActivity {
  activityId: string;
  accountId: string;
  activityType: BrokerAccountActionType;
  status: BrokerAccountActionStatus;
  requestedAt: string;
  completedAt?: string | null;
  actor?: string | null;
  summary: string;
  note?: string | null;
  relatedAlertId?: string | null;
}

export interface BrokerAccountConfiguration {
  accountId: string;
  accountName?: string | null;
  baseCurrency: string;
  configurationVersion: number;
  requestedPolicy: BrokerTradingPolicy;
  effectivePolicy: BrokerTradingPolicy;
  capabilities: BrokerCapabilityFlags;
  allocation: BrokerStrategyAllocationSummary;
  warnings: string[];
  updatedAt?: string | null;
  updatedBy?: string | null;
  audit: BrokerAccountConfigurationAuditRecord[];
}

export interface BrokerTradingPolicy {
  maxOpenPositions?: number | null;
  maxSinglePositionExposure?: BrokerPositionSizeLimit | null;
  allowedSides: BrokerPolicySide[];
  allowedAssetClasses: BrokerPolicyAssetClass[];
  requireOrderConfirmation: boolean;
}

export interface BrokerPositionSizeLimit {
  mode: BrokerPositionSizeMode;
  value: number;
}

export interface BrokerAccountConfigurationAuditRecord {
  auditId: string;
  accountId: string;
  category: BrokerConfigurationAuditCategory;
  outcome: BrokerConfigurationAuditOutcome;
  requestedAt: string;
  actor?: string | null;
  requestId?: string | null;
  grantedRoles: string[];
  summary: string;
  before: Record<string, unknown>;
  after: Record<string, unknown>;
  denialReason?: string | null;
}

export interface BrokerAccountListResponse {
  accounts: BrokerAccountSummary[];
  generatedAt?: string | null;
}

export interface BrokerAccountActionResponse {
  actionId: string;
  accountId: string;
  action: BrokerAccountActionType;
  status: BrokerAccountActionStatus;
  requestedAt: string;
  message?: string | null;
  resultingConnectionHealth?: BrokerConnectionHealth | null;
  tradeReadiness?: TradeReadiness | null;
  syncPaused?: boolean | null;
}

export interface BrokerAccountOnboardingCandidate {
  candidateId: string;
  provider: TradeProvider;
  environment: TradeEnvironment;
  suggestedAccountId: string;
  displayName: string;
  accountNumberMasked?: string | null;
  baseCurrency: string;
  state: BrokerAccountOnboardingCandidateState;
  stateReason?: string | null;
  existingAccountId?: string | null;
  allowedExecutionPostures: BrokerAccountExecutionPosture[];
  blockedExecutionPostureReasons: Record<string, string>;
  canOnboard: boolean;
}

export interface BrokerAccountOnboardingCandidateListResponse {
  candidates: BrokerAccountOnboardingCandidate[];
  discoveryStatus: BrokerAccountOnboardingDiscoveryStatus;
  message: string;
  generatedAt?: string | null;
}

export interface BrokerAccountOnboardingRequest {
  candidateId: string;
  provider: TradeProvider;
  environment: TradeEnvironment;
  displayName: string;
  readiness: TradeReadiness;
  executionPosture: BrokerAccountExecutionPosture;
  initialRefresh: boolean;
  reason: string;
}

export interface BrokerAccountOnboardingResponse {
  account: BrokerAccountSummary;
  configuration?: BrokerAccountConfiguration | null;
  created: boolean;
  reenabled: boolean;
  refreshAction?: BrokerAccountActionResponse | null;
  audit?: BrokerAccountConfigurationAuditRecord | null;
  message: string;
  generatedAt?: string | null;
}

export interface BrokerAccountAllocationUpdateRequest {
  expectedConfigurationVersion?: number | null;
  allocationMode: PortfolioAllocationMode;
  allocatableCapital?: number | null;
  effectiveFrom?: string | null;
  items: BrokerStrategyAllocationItem[];
  notes: string;
}

export interface BrokerTradingPolicyUpdateRequest {
  expectedConfigurationVersion?: number | null;
  requestedPolicy: BrokerTradingPolicy;
}

export interface ReconnectBrokerAccountRequest {
  reason: string;
}

export interface PauseBrokerSyncRequest {
  paused: boolean;
  reason: string;
}

export interface RefreshBrokerAccountRequest {
  scope: BrokerSyncScope;
  force: boolean;
  reason: string;
}

export interface AcknowledgeBrokerAlertRequest {
  note: string;
}

export interface TradeAccountSummary {
  accountId: string;
  name: string;
  provider: TradeProvider;
  environment: TradeEnvironment;
  accountNumberMasked?: string | null;
  baseCurrency: string;
  readiness: TradeReadiness;
  readinessReason?: string | null;
  capabilities: TradeCapabilityFlags;
  cash: number;
  buyingPower: number;
  equity: number;
  openOrderCount: number;
  positionCount: number;
  unresolvedAlertCount: number;
  killSwitchActive: boolean;
  pnl?: TradePnlSnapshot | null;
  lastSyncedAt?: string | null;
  lastTradeAt?: string | null;
  snapshotAsOf?: string | null;
  freshness: TradeDataFreshness;
  policyVersion?: number | null;
  projectedTradingPolicy?: BrokerTradingPolicy | null;
  confirmationRequired: boolean;
}

export interface TradeCapabilityFlags {
  canReadAccount: boolean;
  canReadPositions: boolean;
  canReadOrders: boolean;
  canReadHistory: boolean;
  canPreview: boolean;
  canSubmitPaper: boolean;
  canSubmitSandbox: boolean;
  canSubmitLive: boolean;
  canCancel: boolean;
  supportsMarketOrders: boolean;
  supportsLimitOrders: boolean;
  supportsStopOrders: boolean;
  supportsFractionalQuantity: boolean;
  supportsNotionalOrders: boolean;
  supportsEquities: boolean;
  supportsEtfs: boolean;
  supportsOptions: boolean;
  readOnly: boolean;
  unsupportedReason?: string | null;
}

export interface TradePnlSnapshot {
  realizedPnl?: number | null;
  unrealizedPnl?: number | null;
  dayPnl?: number | null;
  grossExposure?: number | null;
  netExposure?: number | null;
  asOf?: string | null;
}

export interface TradeDataFreshness {
  balancesState: TradeDataFreshnessState;
  positionsState: TradeDataFreshnessState;
  ordersState: TradeDataFreshnessState;
  balancesAsOf?: string | null;
  positionsAsOf?: string | null;
  ordersAsOf?: string | null;
  maxAgeSeconds?: number | null;
  staleReason?: string | null;
}

export interface TradeAccountDetail {
  account: TradeAccountSummary;
  restrictions: string[];
  riskLimits: TradeRiskLimit;
  unresolvedAlerts: string[];
  alerts: TradeDeskAlert[];
  recentAuditEvents: TradeDeskAuditEvent[];
}

export interface TradeRiskLimit {
  maxOrderNotional?: number | null;
  maxDailyNotional?: number | null;
  maxShareQuantity?: number | null;
  allowedAssetClasses: TradeAssetClass[];
  allowedOrderTypes: TradeOrderType[];
  liveTradingAllowed: boolean;
  liveTradingReason?: string | null;
}

export interface TradeDeskAlert {
  alertId: string;
  accountId: string;
  severity: TradeAuditSeverity;
  status: BrokerAlertStatus;
  code: string;
  title: string;
  message: string;
  blocking: boolean;
  observedAt: string;
  acknowledgedAt?: string | null;
  acknowledgedBy?: string | null;
  resolvedAt?: string | null;
  asOfDate?: string | null;
}

export interface TradeDeskAuditEvent {
  eventId: string;
  accountId: string;
  provider: TradeProvider;
  environment: TradeEnvironment;
  eventType: TradeAuditEventType;
  severity: TradeAuditSeverity;
  occurredAt: string;
  actor?: string | null;
  orderId?: string | null;
  providerOrderId?: string | null;
  clientRequestId?: string | null;
  idempotencyKey?: string | null;
  previewId?: string | null;
  confirmationTokenId?: string | null;
  requestId?: string | null;
  statusBefore?: TradeOrderStatus | null;
  statusAfter?: TradeOrderStatus | null;
  summary: string;
  sanitizedError?: string | null;
  denialReason?: string | null;
  grantedRoles: string[];
  details: Record<string, unknown>;
}

export interface TradeAccountListResponse {
  accounts: TradeAccountSummary[];
  generatedAt?: string | null;
}

export interface TradePosition {
  accountId: string;
  symbol: string;
  assetClass: TradeAssetClass;
  quantity: number;
  marketValue: number;
  averageEntryPrice?: number | null;
  lastPrice?: number | null;
  costBasis?: number | null;
  unrealizedPnl?: number | null;
  unrealizedPnlPercent?: number | null;
  dayPnl?: number | null;
  weight?: number | null;
  asOf?: string | null;
}

export interface TradePositionListResponse {
  accountId: string;
  positions: TradePosition[];
  generatedAt?: string | null;
  freshness: TradeDataFreshness;
}

export interface TradeOrder {
  orderId: string;
  accountId: string;
  provider: TradeProvider;
  environment: TradeEnvironment;
  status: TradeOrderStatus;
  symbol: string;
  side: TradeOrderSide;
  orderType: TradeOrderType;
  timeInForce: TradeTimeInForce;
  assetClass: TradeAssetClass;
  clientRequestId?: string | null;
  idempotencyKey?: string | null;
  correlationId?: string | null;
  providerOrderId?: string | null;
  providerCorrelationId?: string | null;
  quantity?: number | null;
  notional?: number | null;
  limitPrice?: number | null;
  stopPrice?: number | null;
  estimatedPrice?: number | null;
  estimatedNotional?: number | null;
  filledQuantity: number;
  averageFillPrice?: number | null;
  submittedAt?: string | null;
  acceptedAt?: string | null;
  filledAt?: string | null;
  cancelledAt?: string | null;
  expiresAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  statusReason?: string | null;
  riskChecks: TradeRiskCheck[];
  reconciliationRequired: boolean;
}

export interface TradeRiskCheck {
  checkId: string;
  code: string;
  label: string;
  status: TradeRiskCheckStatus;
  severity: TradeAuditSeverity;
  blocking: boolean;
  message: string;
  metadata: Record<string, unknown>;
}

export interface TradeOrderHistoryResponse {
  accountId: string;
  orders: TradeOrder[];
  generatedAt?: string | null;
  nextCursor?: string | null;
}

export interface TradeBlotterRow {
  rowId: string;
  accountId: string;
  provider: TradeProvider;
  environment: TradeEnvironment;
  eventType: TradeBlotterEventType;
  occurredAt: string;
  orderId?: string | null;
  providerOrderId?: string | null;
  clientRequestId?: string | null;
  symbol?: string | null;
  side?: TradeOrderSide | null;
  status?: TradeOrderStatus | null;
  quantity?: number | null;
  price?: number | null;
  fees?: number | null;
  realizedPnl?: number | null;
  cashImpact?: number | null;
  note?: string | null;
}

export interface TradeBlotterResponse {
  accountId: string;
  rows: TradeBlotterRow[];
  generatedAt?: string | null;
  nextCursor?: string | null;
}

export interface TradeOrderPreviewRequest {
  accountId: string;
  environment: TradeEnvironment;
  clientRequestId: string;
  symbol: string;
  side: TradeOrderSide;
  orderType: TradeOrderType;
  timeInForce: TradeTimeInForce;
  assetClass: TradeAssetClass;
  quantity?: number | null;
  notional?: number | null;
  limitPrice?: number | null;
  stopPrice?: number | null;
  allowExtendedHours: boolean;
  source: 'manual' | 'rebalance_preview' | 'system';
  strategyRef?: StrategyReferenceInput | null;
}

export interface TradeOrderPreviewResponse {
  previewId: string;
  accountId: string;
  provider: TradeProvider;
  environment: TradeEnvironment;
  order: TradeOrder;
  generatedAt: string;
  expiresAt: string;
  estimatedCost?: number | null;
  estimatedFees: number;
  cashAfter?: number | null;
  buyingPowerAfter?: number | null;
  riskChecks: TradeRiskCheck[];
  warnings: string[];
  blocked: boolean;
  blockReason?: string | null;
  freshness: TradeDataFreshness;
  projectedPolicy?: BrokerTradingPolicy | null;
  policyVersion?: number | null;
  confirmationRequired: boolean;
  orderHash?: string | null;
  confirmationToken?: string | null;
}

export interface TradeOrderPlaceRequest {
  accountId: string;
  environment: TradeEnvironment;
  clientRequestId: string;
  symbol: string;
  side: TradeOrderSide;
  orderType: TradeOrderType;
  timeInForce: TradeTimeInForce;
  assetClass: TradeAssetClass;
  quantity?: number | null;
  notional?: number | null;
  limitPrice?: number | null;
  stopPrice?: number | null;
  allowExtendedHours: boolean;
  source: 'manual' | 'rebalance_preview' | 'system';
  strategyRef?: StrategyReferenceInput | null;
  idempotencyKey: string;
  previewId: string;
  confirmedAt: string;
  confirmedRiskCheckIds: string[];
  policyVersion?: number | null;
  orderHash?: string | null;
  confirmationToken?: string | null;
}

export interface TradeOrderPlaceResponse {
  order: TradeOrder;
  submitted: boolean;
  replayed: boolean;
  reconciliationRequired: boolean;
  auditEventId?: string | null;
  message?: string | null;
  confirmationRequired: boolean;
  policyVersion?: number | null;
}

export interface TradeOrderCancelRequest {
  accountId: string;
  orderId: string;
  clientRequestId: string;
  idempotencyKey: string;
  reason: string;
}

export interface TradeOrderCancelResponse {
  order: TradeOrder;
  cancelAccepted: boolean;
  replayed: boolean;
  reconciliationRequired: boolean;
  auditEventId?: string | null;
  message?: string | null;
}

export interface TradeDeskAuditEventListResponse {
  accountId: string;
  events: TradeDeskAuditEvent[];
  generatedAt?: string | null;
  nextCursor?: string | null;
}

export interface CreateNotificationRequest {
  sourceRepo: string;
  sourceSystem?: string | null;
  clientRequestId: string;
  idempotencyKey: string;
  kind: NotificationKind;
  title: string;
  description: string;
  targetUrl?: string | null;
  recipients: NotificationRecipient[];
  expiresAt?: string | null;
  tradeApproval?: TradeApprovalPayload | null;
  metadata: Record<string, unknown>;
}

export interface NotificationRecipient {
  recipientId?: string | null;
  displayName?: string | null;
  email?: string | null;
  phoneNumber?: string | null;
  channels: NotificationDeliveryChannel[];
}

export interface TradeApprovalPayload {
  accountId: string;
  previewId: string;
  orderHash: string;
  placeIdempotencyKey: string;
  order: TradeOrderPreviewRequest;
}

export interface NotificationStatusResponse {
  requestId: string;
  kind: NotificationKind;
  status: NotificationRequestStatus;
  sourceRepo: string;
  sourceSystem?: string | null;
  clientRequestId: string;
  title: string;
  description: string;
  targetUrl?: string | null;
  createdAt: string;
  updatedAt: string;
  expiresAt?: string | null;
  decisionStatus: NotificationDecisionStatus;
  decision?: NotificationDecision | null;
  decidedAt?: string | null;
  decidedBy?: string | null;
  executionStatus: NotificationExecutionStatus;
  executionOrderId?: string | null;
  executionMessage?: string | null;
  deliveries: NotificationDeliveryResult[];
  tradeApproval?: TradeApprovalDisplay | null;
}

export interface NotificationDeliveryResult {
  recipientId: string;
  channel: NotificationDeliveryChannel;
  address: string;
  status: NotificationDeliveryStatus;
  provider?: string | null;
  providerMessageId?: string | null;
  attemptedAt?: string | null;
  sanitizedError?: string | null;
}

export interface TradeApprovalDisplay {
  accountId: string;
  previewId: string;
  orderHash: string;
  environment: TradeEnvironment;
  symbol: string;
  side: TradeOrderSide;
  orderType: TradeOrderType;
  timeInForce: TradeTimeInForce;
  quantity?: number | null;
  notional?: number | null;
  limitPrice?: number | null;
  stopPrice?: number | null;
}

export interface NotificationActionDetailResponse {
  requestId: string;
  tokenId: string;
  kind: NotificationKind;
  title: string;
  description: string;
  targetUrl?: string | null;
  createdAt: string;
  expiresAt?: string | null;
  decisionStatus: NotificationDecisionStatus;
  executionStatus: NotificationExecutionStatus;
  tradeApproval?: TradeApprovalDisplay | null;
}

export interface NotificationDecisionRequest {
  decision: NotificationDecision;
  reason: string;
}

export interface PortfolioAccount {
  accountId: string;
  name: string;
  description: string;
  status: 'draft' | 'active' | 'archived';
  mode: 'internal_model_managed';
  accountingDepth: 'position_level';
  cadenceMode: 'strategy_native';
  rebalanceCadence: 'daily' | 'weekly' | 'monthly';
  rebalanceAnchor: string;
  baseCurrency: string;
  benchmarkSymbol?: string | null;
  inceptionDate: string;
  mandate: string;
  latestRevision?: number | null;
  activeRevision?: number | null;
  activePortfolioName?: string | null;
  activePortfolioVersion?: number | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  lastMaterializedAt?: string | null;
  openAlertCount: number;
}

export interface PortfolioAccountDetailResponse {
  account: PortfolioAccount;
  revision?: PortfolioAccountRevision | null;
  activeAssignment?: PortfolioAssignment | null;
  recentLedgerEvents: PortfolioLedgerEvent[];
}

export interface PortfolioAccountRevision {
  accountId: string;
  version: number;
  name: string;
  description: string;
  mandate: string;
  status: 'draft' | 'active' | 'archived';
  mode: 'internal_model_managed';
  accountingDepth: 'position_level';
  cadenceMode: 'strategy_native';
  rebalanceCadence: 'daily' | 'weekly' | 'monthly';
  rebalanceAnchor: string;
  baseCurrency: string;
  benchmarkSymbol?: string | null;
  inceptionDate: string;
  notes: string;
  createdAt?: string | null;
  createdBy?: string | null;
}

export interface PortfolioAssignment {
  assignmentId: string;
  accountId: string;
  accountVersion: number;
  portfolioName: string;
  portfolioVersion: number;
  effectiveFrom: string;
  effectiveTo?: string | null;
  status: 'scheduled' | 'active' | 'ended';
  notes: string;
  createdAt?: string | null;
}

export interface PortfolioLedgerEvent {
  effectiveAt: string;
  eventType: 'opening_balance' | 'deposit' | 'withdrawal' | 'fee' | 'dividend' | 'rebalance_buy' | 'rebalance_sell' | 'correction';
  currency: string;
  cashAmount: number;
  symbol?: string | null;
  quantity?: number | null;
  price?: number | null;
  commission: number;
  slippageCost: number;
  description: string;
  eventId: string;
  accountId: string;
}

export interface PortfolioAccountListResponse {
  accounts: PortfolioAccount[];
}

export interface PortfolioAccountUpsertRequest {
  name: string;
  description: string;
  mandate: string;
  rebalanceCadence?: 'daily' | 'weekly' | 'monthly' | null;
  rebalanceAnchor?: string | null;
  baseCurrency: string;
  benchmarkSymbol?: string | null;
  inceptionDate: string;
  openingCash?: number | null;
  notes: string;
}

export interface PortfolioAlertListResponse {
  alerts: PortfolioAlert[];
  total: number;
  openCount: number;
}

export interface PortfolioAlert {
  alertId: string;
  accountId: string;
  severity: TradeAuditSeverity;
  status: BrokerAlertStatus;
  code: string;
  title: string;
  description: string;
  detectedAt: string;
  acknowledgedAt?: string | null;
  acknowledgedBy?: string | null;
  resolvedAt?: string | null;
  asOf?: string | null;
}

export interface PortfolioAssignmentRequest {
  accountVersion: number;
  portfolioName: string;
  portfolioVersion: number;
  effectiveFrom: string;
  notes: string;
}

export interface PortfolioDefinition {
  name: string;
  description: string;
  benchmarkSymbol?: string | null;
  status: 'draft' | 'active' | 'archived';
  latestVersion?: number | null;
  activeVersion?: number | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface PortfolioDefinitionDetailResponse {
  portfolio: PortfolioDefinition;
  activeRevision?: PortfolioRevision | null;
  revisions: PortfolioRevision[];
}

export interface PortfolioRevision {
  portfolioName: string;
  version: number;
  description: string;
  benchmarkSymbol?: string | null;
  allocationMode: PortfolioAllocationMode;
  allocatableCapital?: number | null;
  allocations: PortfolioSleeveAllocation[];
  notes: string;
  publishedAt?: string | null;
  createdAt?: string | null;
  createdBy?: string | null;
}

export interface PortfolioSleeveAllocation {
  sleeveId: string;
  sleeveName: string;
  strategy: StrategyVersionReference;
  allocationMode: PortfolioAllocationMode;
  targetWeight?: number | null;
  targetNotionalBaseCcy?: number | null;
  derivedWeight?: number | null;
  minWeight?: number | null;
  maxWeight?: number | null;
  enabled: boolean;
  rebalancePriority: number;
  notes: string;
}

export interface StrategyVersionReference {
  strategyName: string;
  strategyVersion: number;
}

export interface PortfolioHistoryResponse {
  points: PortfolioHistoryPoint[];
  totalPoints: number;
  truncated: boolean;
}

export interface PortfolioHistoryPoint {
  asOf: string;
  nav: number;
  cash: number;
  grossExposure: number;
  netExposure: number;
  periodPnl?: number | null;
  periodReturn?: number | null;
  cumulativePnl?: number | null;
  cumulativeReturn?: number | null;
  drawdown?: number | null;
  turnover?: number | null;
  costDragBps?: number | null;
}

export interface PortfolioLedgerEventPayload {
  effectiveAt: string;
  eventType: 'opening_balance' | 'deposit' | 'withdrawal' | 'fee' | 'dividend' | 'rebalance_buy' | 'rebalance_sell' | 'correction';
  currency: string;
  cashAmount: number;
  symbol?: string | null;
  quantity?: number | null;
  price?: number | null;
  commission: number;
  slippageCost: number;
  description: string;
}

export interface PortfolioListResponse {
  portfolios: PortfolioDefinition[];
}

export interface PortfolioPositionListResponse {
  positions: PortfolioPosition[];
  total: number;
  limit: number;
  offset: number;
}

export interface PortfolioPosition {
  asOf: string;
  symbol: string;
  quantity: number;
  marketValue: number;
  weight: number;
  averageCost?: number | null;
  lastPrice?: number | null;
  unrealizedPnl?: number | null;
  realizedPnl?: number | null;
  contributors: PortfolioPositionContributor[];
}

export interface PortfolioPositionContributor {
  sleeveId: string;
  strategyName: string;
  strategyVersion: number;
  quantity: number;
  marketValue: number;
  weight: number;
}

export interface PortfolioRebalanceApplyRequest {
  proposalId: string;
  executedAt: string;
  notes: string;
}

export interface PortfolioRebalancePreviewRequest {
  asOf: string;
  notes: string;
}

export interface RebalanceProposal {
  proposalId: string;
  accountId: string;
  asOf: string;
  portfolioName: string;
  portfolioVersion: number;
  blocked: boolean;
  warnings: string[];
  blockedReasons: string[];
  estimatedCashImpact: number;
  estimatedTurnover: number;
  trades: RebalanceTradeProposal[];
}

export interface RebalanceTradeProposal {
  sleeveId: string;
  symbol: string;
  side: TradeOrderSide;
  quantity: number;
  estimatedPrice: number;
  estimatedNotional: number;
  estimatedCommission: number;
  estimatedSlippageCost: number;
}

export interface PortfolioSnapshot {
  accountId: string;
  accountName: string;
  asOf: string;
  nav: number;
  cash: number;
  grossExposure: number;
  netExposure: number;
  sinceInceptionPnl: number;
  sinceInceptionReturn: number;
  currentDrawdown: number;
  maxDrawdown?: number | null;
  openAlertCount: number;
  activeAssignment?: PortfolioAssignment | null;
  freshness: FreshnessStatus[];
  slices: StrategySliceAttribution[];
}

export interface FreshnessStatus {
  domain: 'valuation' | 'positions' | 'risk' | 'attribution' | 'ledger' | 'alerts';
  state: 'fresh' | 'stale' | 'error' | 'missing';
  asOf?: string | null;
  checkedAt?: string | null;
  reason: string;
}

export interface StrategySliceAttribution {
  asOf: string;
  sleeveId: string;
  strategyName: string;
  strategyVersion: number;
  targetWeight: number;
  actualWeight: number;
  marketValue: number;
  grossExposure: number;
  netExposure: number;
  pnlContribution: number;
  returnContribution: number;
  drawdownContribution: number;
  turnover?: number | null;
  sinceInceptionReturn?: number | null;
}

export interface PortfolioUpsertRequest {
  name: string;
  description: string;
  benchmarkSymbol?: string | null;
  allocationMode: PortfolioAllocationMode;
  allocatableCapital?: number | null;
  allocations: PortfolioSleeveAllocation[];
  notes: string;
}

export interface CongressTradeEvent {
  event_id: string;
  source_name: string;
  source_event_key: string;
  member_id?: string | null;
  member_name: string;
  chamber: 'house' | 'senate' | 'joint' | 'unknown';
  party?: string | null;
  state?: string | null;
  district?: string | null;
  committee_names: string[];
  traded_at: string;
  filed_at?: string | null;
  notified_at?: string | null;
  relationship_type: 'self' | 'spouse' | 'dependent_child' | 'joint' | 'unknown';
  transaction_type: 'purchase' | 'sale' | 'partial_sale' | 'exchange' | 'other';
  filing_status: 'new' | 'amended' | 'late' | 'unknown';
  amendment_flag: boolean;
  late_filing_days?: number | null;
  asset_name: string;
  asset_description?: string | null;
  asset_type?: string | null;
  issuer_name?: string | null;
  issuer_ticker?: string | null;
  amount_lower_usd?: number | null;
  amount_upper_usd?: number | null;
  amount_bucket_label?: string | null;
  comments?: string | null;
  excess_return?: number | null;
  confidence?: number | null;
  mapping_status: 'pending_review' | 'mapped' | 'ignored';
  created_at?: string | null;
  updated_at?: string | null;
}

export interface CongressTradeEventListResponse {
  events: CongressTradeEvent[];
  total: number;
  limit: number;
  offset: number;
}

export interface CongressTradeVersion {
  version_id: string;
  event_id: string;
  version_seq: number;
  version_kind: string;
  version_observed_at: string;
  event: CongressTradeEvent;
}

export interface GovernmentContractEvent {
  event_id: string;
  source_name: string;
  source_event_key: string;
  event_type: 'opportunity' | 'award' | 'modification' | 'option_exercise' | 'obligation' | 'outlay' | 'termination' | 'cancellation' | 'protest' | 'other';
  event_at: string;
  recipient_name: string;
  recipient_ticker?: string | null;
  awarding_agency: string;
  funding_agency?: string | null;
  award_id?: string | null;
  parent_award_id?: string | null;
  opportunity_id?: string | null;
  solicitation_id?: string | null;
  title: string;
  description?: string | null;
  award_amount_usd?: number | null;
  obligation_delta_usd?: number | null;
  outlay_delta_usd?: number | null;
  cumulative_obligation_usd?: number | null;
  modification_number?: string | null;
  option_exercise_flag: boolean;
  termination_flag: boolean;
  cancellation_flag: boolean;
  protest_flag: boolean;
  naics_code?: string | null;
  psc_code?: string | null;
  competition_type?: string | null;
  set_aside_type?: string | null;
  contract_vehicle?: string | null;
  place_of_performance_country?: string | null;
  place_of_performance_state?: string | null;
  confidence?: number | null;
  mapping_status: 'pending_review' | 'mapped' | 'ignored';
  created_at?: string | null;
  updated_at?: string | null;
}

export interface GovernmentContractEventListResponse {
  events: GovernmentContractEvent[];
  total: number;
  limit: number;
  offset: number;
}

export interface GovernmentContractVersion {
  version_id: string;
  event_id: string;
  version_seq: number;
  version_kind: string;
  version_observed_at: string;
  event: GovernmentContractEvent;
}

export interface IssuerGovernmentSignalDaily {
  as_of_date: string;
  symbol: string;
  issuer_name?: string | null;
  congress_purchase_count_1d: number;
  congress_purchase_count_7d: number;
  congress_purchase_count_30d: number;
  congress_purchase_count_90d: number;
  congress_sale_count_1d: number;
  congress_sale_count_7d: number;
  congress_sale_count_30d: number;
  congress_sale_count_90d: number;
  congress_net_amount_proxy_usd_30d: number;
  congress_net_amount_proxy_usd_90d: number;
  congress_amendment_rate_90d: number;
  congress_late_filing_rate_90d: number;
  congress_unique_members_90d: number;
  congress_unique_committees_90d: number;
  contract_award_count_30d: number;
  contract_award_count_90d: number;
  contract_obligation_delta_usd_30d: number;
  contract_obligation_delta_usd_90d: number;
  contract_outlay_delta_usd_30d: number;
  contract_outlay_delta_usd_90d: number;
  contract_modification_count_90d: number;
  contract_option_exercise_count_90d: number;
  contract_termination_count_90d: number;
  contract_cancellation_count_90d: number;
  contract_protest_count_90d: number;
  contract_unique_awarding_agencies_90d: number;
  contract_unique_naics_90d: number;
  contract_unique_psc_90d: number;
  last_congress_trade_at?: string | null;
  last_contract_event_at?: string | null;
  mapping_status: 'pending_review' | 'mapped' | 'ignored';
}

export interface GovernmentSignalAlert {
  alert_id: string;
  symbol: string;
  as_of_date: string;
  alert_type: 'congress_trade' | 'contract_event' | 'composite';
  severity: 'low' | 'medium' | 'high' | 'critical';
  title: string;
  summary: string;
  congress_signal_score?: number | null;
  contract_signal_score?: number | null;
  composite_signal_score?: number | null;
  source_event_ids: string[];
  created_at?: string | null;
}

export interface GovernmentSignalAlertListResponse {
  alerts: GovernmentSignalAlert[];
  total: number;
  limit: number;
  offset: number;
}

export interface GovernmentSignalMappingReviewResponse {
  items: GovernmentSignalMappingReviewItem[];
  total: number;
  limit: number;
  offset: number;
}

export interface GovernmentSignalMappingReviewItem {
  mapping_id: string;
  source_name: string;
  entity_type: string;
  raw_key: string;
  raw_name: string;
  proposed_symbol?: string | null;
  confidence?: number | null;
  status: 'pending_review' | 'mapped' | 'ignored';
  reason?: string | null;
  updated_at?: string | null;
}

export interface GovernmentSignalMappingOverrideRequest {
  action: 'map' | 'ignore' | 'defer';
  symbol?: string | null;
  reason?: string | null;
}

export interface GovernmentSignalMappingOverrideResponse {
  mapping_id: string;
  status: 'pending_review' | 'mapped' | 'ignored';
  symbol?: string | null;
  updated_at: string;
}

export interface GovernmentSignalIssuerSummaryResponse {
  symbol: string;
  issuer_name?: string | null;
  as_of_date: string;
  issuer_daily: IssuerGovernmentSignalDaily;
  recent_congress_trades: CongressTradeEvent[];
  recent_contract_events: GovernmentContractEvent[];
  active_alerts: GovernmentSignalAlert[];
}

export interface GovernmentSignalPortfolioExposureRequest {
  as_of_date?: string | null;
  holdings: GovernmentSignalPortfolioHolding[];
}

export interface GovernmentSignalPortfolioHolding {
  symbol: string;
  shares?: number | null;
  market_value?: number | null;
  portfolio_weight?: number | null;
}

export interface GovernmentSignalPortfolioExposureResponse {
  as_of_date: string;
  holdings_analyzed: number;
  matched_holdings: number;
  unmatched_symbols: string[];
  total_market_value?: number | null;
  total_portfolio_weight?: number | null;
  exposures: GovernmentSignalPortfolioIssuerExposure[];
}

export interface GovernmentSignalPortfolioIssuerExposure {
  symbol: string;
  issuer_name?: string | null;
  matched: boolean;
  market_value?: number | null;
  portfolio_weight?: number | null;
  issuer_daily?: IssuerGovernmentSignalDaily | null;
  alerts: GovernmentSignalAlert[];
}

export interface AiChatRequest {
  prompt: string;
  role?: string | null;
  systemInstructions?: string | null;
}

export interface SymbolCleanupWorkItem {
  workId: string;
  runId: string;
  symbol: string;
  status: 'queued' | 'claimed' | 'completed' | 'failed';
  requestedFields: ('security_type_norm' | 'exchange_mic' | 'country_of_risk' | 'sector_norm' | 'industry_group_norm' | 'industry_norm' | 'is_adr' | 'is_etf' | 'is_cef' | 'is_preferred' | 'share_class' | 'listing_status_norm' | 'issuer_summary_short')[];
  attemptCount: number;
  executionName?: string | null;
  claimedAt?: string | null;
  lastError?: string | null;
}

export interface SymbolCleanupRunSummary {
  runId: string;
  status: BrokerSyncRunStatus;
  mode: 'fill_missing' | 'full_reconcile';
  queuedCount: number;
  claimedCount: number;
  completedCount: number;
  failedCount: number;
  acceptedUpdateCount: number;
  rejectedUpdateCount: number;
  lockedSkipCount: number;
  overwriteCount: number;
  startedAt?: string | null;
  completedAt?: string | null;
}

export interface SymbolEnrichmentResolveRequest {
  symbol: string;
  overwriteMode: 'fill_missing' | 'full_reconcile';
  requestedFields: ('security_type_norm' | 'exchange_mic' | 'country_of_risk' | 'sector_norm' | 'industry_group_norm' | 'industry_norm' | 'is_adr' | 'is_etf' | 'is_cef' | 'is_preferred' | 'share_class' | 'listing_status_norm' | 'issuer_summary_short')[];
  providerFacts: SymbolProviderFacts;
  currentProfile?: SymbolProfileValues | null;
}

export interface SymbolProviderFacts {
  symbol: string;
  name?: string | null;
  description?: string | null;
  sector?: string | null;
  industry?: string | null;
  industry2?: string | null;
  country?: string | null;
  exchange?: string | null;
  assetType?: string | null;
  ipoDate?: string | null;
  delistingDate?: string | null;
  status?: string | null;
  isOptionable?: boolean | null;
  sourceNasdaq?: boolean | null;
  sourceMassive?: boolean | null;
  sourceAlphaVantage?: boolean | null;
}

export interface SymbolProfileValues {
  security_type_norm?: string | null;
  exchange_mic?: string | null;
  country_of_risk?: string | null;
  sector_norm?: string | null;
  industry_group_norm?: string | null;
  industry_norm?: string | null;
  is_adr?: boolean | null;
  is_etf?: boolean | null;
  is_cef?: boolean | null;
  is_preferred?: boolean | null;
  share_class?: string | null;
  listing_status_norm?: string | null;
  issuer_summary_short?: string | null;
}

export interface SymbolEnrichmentResolveResponse {
  symbol: string;
  profile: SymbolProfileValues;
  model?: string | null;
  confidence?: number | null;
  sourceFingerprint?: string | null;
  warnings: string[];
}

export interface SymbolProfileCurrent {
  security_type_norm?: string | null;
  exchange_mic?: string | null;
  country_of_risk?: string | null;
  sector_norm?: string | null;
  industry_group_norm?: string | null;
  industry_norm?: string | null;
  is_adr?: boolean | null;
  is_etf?: boolean | null;
  is_cef?: boolean | null;
  is_preferred?: boolean | null;
  share_class?: string | null;
  listing_status_norm?: string | null;
  issuer_summary_short?: string | null;
  symbol: string;
  sourceKind: 'provider' | 'ai' | 'derived' | 'override';
  sourceFingerprint?: string | null;
  aiModel?: string | null;
  aiConfidence?: number | null;
  validationStatus: 'accepted' | 'rejected' | 'pending' | 'locked';
  marketCapUsd?: number | null;
  marketCapBucket?: string | null;
  avgDollarVolume20d?: number | null;
  liquidityBucket?: string | null;
  isTradeableCommonEquity?: boolean | null;
  dataCompletenessScore?: number | null;
  updatedAt?: string | null;
}

export interface SymbolProfileHistoryEntry {
  historyId: string;
  symbol: string;
  fieldName: 'security_type_norm' | 'exchange_mic' | 'country_of_risk' | 'sector_norm' | 'industry_group_norm' | 'industry_norm' | 'is_adr' | 'is_etf' | 'is_cef' | 'is_preferred' | 'share_class' | 'listing_status_norm' | 'issuer_summary_short';
  previousValue?: string | number | boolean | null;
  newValue?: string | number | boolean | null;
  sourceKind: 'provider' | 'ai' | 'derived' | 'override';
  aiModel?: string | null;
  aiConfidence?: number | null;
  changeReason?: string | null;
  runId?: string | null;
  updatedAt: string;
}

export interface SymbolProfileOverride {
  symbol: string;
  fieldName: 'security_type_norm' | 'exchange_mic' | 'country_of_risk' | 'sector_norm' | 'industry_group_norm' | 'industry_norm' | 'is_adr' | 'is_etf' | 'is_cef' | 'is_preferred' | 'share_class' | 'listing_status_norm' | 'issuer_summary_short';
  value?: string | number | boolean | null;
  isLocked: boolean;
  updatedBy?: string | null;
  updatedAt?: string | null;
}

export interface SymbolEnrichmentSummaryResponse {
  backlogCount: number;
  lastRun?: SymbolCleanupRunSummary | null;
  activeRun?: SymbolCleanupRunSummary | null;
  validationFailureCount: number;
  lockCount: number;
}

export interface SymbolEnrichmentSymbolListItem {
  symbol: string;
  name?: string | null;
  status: 'accepted' | 'rejected' | 'pending' | 'locked';
  sourceKind: 'provider' | 'ai' | 'derived' | 'override';
  updatedAt?: string | null;
  missingFieldCount: number;
  lockedFieldCount: number;
  dataCompletenessScore?: number | null;
}

export interface SymbolEnrichmentSymbolDetailResponse {
  providerFacts: SymbolProviderFacts;
  currentProfile?: SymbolProfileCurrent | null;
  overrides: SymbolProfileOverride[];
  history: SymbolProfileHistoryEntry[];
}

export interface SymbolEnrichmentEnqueueRequest {
  symbols: string[];
  fullScan: boolean;
  overwriteMode: 'fill_missing' | 'full_reconcile';
  maxSymbols?: number | null;
}

export interface IntradayWatchlistSummary {
  watchlistId: string;
  name: string;
  description?: string | null;
  enabled: boolean;
  symbolCount: number;
  pollIntervalMinutes: number;
  refreshCooldownMinutes: number;
  autoRefreshEnabled: boolean;
  marketSession: 'us_equities_regular';
  nextDueAt?: string | null;
  lastRunAt?: string | null;
  updatedAt?: string | null;
}

export interface IntradayWatchlistDetail {
  watchlistId: string;
  name: string;
  description?: string | null;
  enabled: boolean;
  symbolCount: number;
  pollIntervalMinutes: number;
  refreshCooldownMinutes: number;
  autoRefreshEnabled: boolean;
  marketSession: 'us_equities_regular';
  nextDueAt?: string | null;
  lastRunAt?: string | null;
  updatedAt?: string | null;
  symbols: string[];
  createdAt?: string | null;
}

export interface IntradayWatchlistUpsertRequest {
  name: string;
  description?: string | null;
  enabled: boolean;
  symbols: string[];
  pollIntervalMinutes: number;
  refreshCooldownMinutes: number;
  autoRefreshEnabled: boolean;
  marketSession: 'us_equities_regular';
}

export interface IntradayWatchlistSymbolAppendRequest {
  symbols: string[];
  queueRun: boolean;
  reason?: string | null;
}

export interface IntradayWatchlistSymbolAppendResponse {
  watchlist: IntradayWatchlistDetail;
  addedSymbols: string[];
  alreadyPresentSymbols: string[];
  queuedRun?: IntradayMonitorRunSummary | null;
  runSkippedReason?: IntradayWatchlistSymbolAppendRunSkippedReason | null;
}

export interface IntradayMonitorRunSummary {
  runId: string;
  watchlistId: string;
  watchlistName?: string | null;
  triggerKind: 'scheduled' | 'manual';
  status: 'queued' | 'claimed' | 'completed' | 'failed';
  forceRefresh: boolean;
  symbolCount: number;
  observedSymbolCount: number;
  eligibleRefreshCount: number;
  refreshBatchCount: number;
  executionName?: string | null;
  dueAt?: string | null;
  queuedAt?: string | null;
  claimedAt?: string | null;
  completedAt?: string | null;
  lastError?: string | null;
}

export interface IntradaySymbolStatus {
  watchlistId?: string | null;
  symbol: string;
  monitorStatus: 'idle' | 'observed' | 'refresh_queued' | 'refreshed' | 'failed';
  lastSnapshotAt?: string | null;
  lastObservedPrice?: number | null;
  lastSuccessfulMarketRefreshAt?: string | null;
  lastRunId?: string | null;
  lastError?: string | null;
  updatedAt?: string | null;
}

export interface IntradayMonitorEvent {
  eventId?: string | null;
  runId?: string | null;
  watchlistId?: string | null;
  symbol?: string | null;
  eventType: string;
  severity: 'info' | 'warning' | 'error';
  message: string;
  details: Record<string, unknown>;
  createdAt?: string | null;
}

export interface IntradayMonitorClaimRequest {
  executionName?: string | null;
}

export interface IntradayMonitorClaimResponse {
  run?: IntradayMonitorRunSummary | null;
  watchlist?: IntradayWatchlistDetail | null;
  currentSymbolStatuses: IntradaySymbolStatus[];
  claimToken?: string | null;
}

export interface IntradayMonitorCompleteRequest {
  claimToken: string;
  symbolStatuses: IntradaySymbolStatus[];
  events: IntradayMonitorEvent[];
  refreshSymbols: string[];
}

export interface IntradayMonitorFailRequest {
  claimToken: string;
  error: string;
}

export interface IntradayRefreshBatchSummary {
  batchId: string;
  runId: string;
  watchlistId: string;
  watchlistName?: string | null;
  domain: string;
  bucketLetter: string;
  status: 'queued' | 'claimed' | 'completed' | 'failed';
  symbols: string[];
  symbolCount: number;
  executionName?: string | null;
  claimedAt?: string | null;
  completedAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  lastError?: string | null;
}

export interface IntradayRefreshClaimRequest {
  executionName?: string | null;
}

export interface IntradayRefreshClaimResponse {
  batch?: IntradayRefreshBatchSummary | null;
  claimToken?: string | null;
}

export interface IntradayRefreshCompleteRequest {
  claimToken: string;
}

export interface IntradayRefreshFailRequest {
  claimToken: string;
  error: string;
}

export interface AiChatStartedEvent {
  sequenceNumber: number;
  event: 'started';
  data: AiChatStartedData;
}

export interface AiChatStartedData {
  requestId: string;
  model: string;
  providerResponseId?: string | null;
}

export interface AiChatStatusEvent {
  sequenceNumber: number;
  event: 'status';
  data: AiChatStatusData;
}

export interface AiChatStatusData {
  code: string;
  message: string;
  providerResponseId?: string | null;
}

export interface AiChatReasoningSummaryDeltaEvent {
  sequenceNumber: number;
  event: 'reasoning_summary_delta';
  data: AiChatReasoningSummaryDeltaData;
}

export interface AiChatReasoningSummaryDeltaData {
  delta: string;
}

export interface AiChatOutputTextDeltaEvent {
  sequenceNumber: number;
  event: 'output_text_delta';
  data: AiChatOutputTextDeltaData;
}

export interface AiChatOutputTextDeltaData {
  delta: string;
}

export interface AiChatCompletedEvent {
  sequenceNumber: number;
  event: 'completed';
  data: AiChatCompletedData;
}

export interface AiChatCompletedData {
  requestId: string;
  model: string;
  providerResponseId?: string | null;
  outputText: string;
  reasoningSummary: string;
  finishReason?: string | null;
}

export interface AiChatErrorEvent {
  sequenceNumber: number;
  event: 'error';
  data: AiChatErrorData;
}

export interface AiChatErrorData {
  error: AiChatError;
}

export interface AiChatError {
  code: string;
  message: string;
  retryable: boolean;
}
